# ###############################
# Load global variables
# ###############################
source(file.path("miscellaneous.R"))

# ###############################
# Load required libraries
# ###############################
library(tidyverse)

library(ape) # read.nexus
library(ggtree)
library(tidytree) # tree_subset
library(ggnewscale) # new_scale_fill

library(igraph) # for clustering

library(buildmer)
library(performance) # icc
library(lme4) # glmer, glmerControl
library(glmmTMB) # glmmTMB
library(gamlss) # gamlss
library(emmeans)

library(ggplot2)
library(ggtext) # element_markdown
library(cowplot) # plot_grid

count <- dplyr::count # Sometimes, if you run multiple scripts in one session, you can get "count" from "mclust", which can cause this script to fail. This line is to make sure that "count" is from "dplyr".

# ###############################
# Load and prepare tree and metadata
# ###############################
# Tree
# -------------------------------
tree <- read.nexus(tree_filepath)
tree$tip.label <- stringr::str_replace(tree$tip.label, "^'(.*)'$", "\\1") # to remove single quotes at the beginning and end of each sequence name

# Sequence metadata
# -------------------------------
seq_metadata <- read.delim(seq_metadata_filepath, header = TRUE, sep = "\t") %>%
  mutate(
    collection_date = as.Date(collection_date, format = "%d/%b/%Y"),
    major_lineage = factor(major_lineage, names(major_lineage_cols)),
    region = factor(region, levels = names(BMR_cols))
  ) %>%
  filter(seq_id %in% tree$tip.label)

# Participant metadata
# -------------------------------
participant_metadata <- read.delim(participant_metadata_filepath, header = TRUE, sep = "\t") %>% 
  select(
    seq_id, # for joining with seq_metadata
    family_id, # for joining with HH_metadata
    age_cat,
    sex,
    overall_res_end_with_symp_severity,
  ) %>%
  mutate(
    age_cat = factor(age_cat, c("Child", "Adult")),
    sex = factor(sex, c("Female", "Male")),
    overall_res_end_with_symp_severity = factor(overall_res_end_with_symp_severity, levels = names(overall_res_end_with_symp_severity_cols)),
  )

# Add first_HH_case_age_cat to participant_metadata
# -------------------------------
first_HH_case_age_cat_dat <- read.delim(HH_metadata_filepath, header = TRUE, sep = "\t") %>%
  select(family_id, first_HH_case_age_cat) %>% unique %>%
  mutate(
    first_HH_case_age_cat = ifelse(first_HH_case_age_cat == "Adult & child", "Adult", first_HH_case_age_cat),
    first_HH_case_age_cat = recode_factor(factor(first_HH_case_age_cat), "Child" = "Child-first household", "Adult" = "Adult-first household"),
    first_HH_case_age_cat = factor(first_HH_case_age_cat, c("Child-first household", "Adult-first household"))
  )

participant_metadata <- left_join(
  participant_metadata,
  first_HH_case_age_cat_dat,
  by = "family_id") %>% 
  relocate(first_HH_case_age_cat)

# Join participant_metadata with seq_metadata
# -------------------------------
seq_metadata <- left_join(
  seq_metadata,
  participant_metadata %>% select(-family_id),
  by = "seq_id"
)

# Add HH_with_complete_seq_dat to seq_metadata
# -------------------------------
HH_with_complete_seq_dat <- participant_metadata %>%
  select(family_id, overall_res_end_with_symp_severity, seq_id) %>%
  filter(str_detect(overall_res_end_with_symp_severity, "Pos")) %>%
  group_by(family_id) %>%
  summarise(
    N_pos = n(),
    seq_avail = sum(!is.na(seq_id)) / N_pos,
    .groups = "drop"
  ) %>%
  filter(seq_avail == 1) %>%
  pull(family_id)

seq_metadata <- seq_metadata %>% 
  mutate(HH_with_complete_seq_dat = family_id %in% HH_with_complete_seq_dat, .after = family_id)

# Compute some basic sequence stats
# -------------------------------
# All sequences
seq_num_all <- read.delim(seq_metadata_filepath, header = TRUE, sep = "\t") %>% nrow + 1 #"MN908947.3"--Severe acute respiratory syndrome coronavirus 2 isolate Wuhan-Hu-1, complete genome--isn't in the dataframe, but is in the tree, included for rooting.
seq_num_all
# [1] 7716

# Sequences generated by our study
seq_num_this_study <- read.delim(seq_metadata_filepath, header = TRUE, sep = "\t") %>% filter(source == "This study") %>% nrow()
seq_num_this_study
# [1] 128

# Public sequences before outlier removal
seq_num_public_before_outlier_removal <- seq_num_all - seq_num_this_study
seq_num_public_before_outlier_removal
# [1] 7588

# Public sequences after outlier removal
seq_num_public_after_outlier_removal <- seq_metadata %>% filter(source != "This study") %>% nrow + 1
seq_num_public_after_outlier_removal
# [1] 7519

# Outlier sequences
seq_num_outliers <- seq_num_public_before_outlier_removal - seq_num_public_after_outlier_removal
seq_num_outliers
# [1] 69

# ###############################
# Plot Figure 3A: Full time-calibrated phylogeny
# ###############################
# Base plot
# -------------------------------
Figure_3A <- ggtree(
  tr = tree, 
  mrsd = seq_metadata %>% 
    pull(collection_date) %>% as.Date() %>% 
    sort(decreasing = TRUE) %>% head(1),
  ladderize = FALSE,
) %<+% seq_metadata

# Highlight our sequences with red tips
# -------------------------------
Figure_3A <- Figure_3A + 
  geom_tippoint(
    mapping = aes(x = x, y = y),
    data = subset(Figure_3A$data, source == "This study"),
    color = "red", size = 1, shape = 16
  )

# Add lineage and region heatmaps to the plot
# -------------------------------
o = 0.2 # heatmap offset

Figure_3A <- gheatmap(
  p = Figure_3A,
  data = seq_metadata %>% select(seq_id, major_lineage) %>% column_to_rownames(var = "seq_id"),
  offset = o*0, width = 0.03,
  color = NULL, 
  colnames = TRUE, custom_column_labels = c("Major\nlineage"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2) +
  scale_fill_manual(
    breaks = names(major_lineage_cols),
    values = major_lineage_cols,
    guide = guide_legend(title = "Major\nlineage", ncol = 1, order = 1)
  ) + aes(x = x, y = y) # For some reason, this is needed to make the code works...

Figure_3A <- gheatmap(
  p = Figure_3A + new_scale_fill(),
  data = seq_metadata %>% select(seq_id, region) %>% column_to_rownames(var = "seq_id"),
  offset = o*1, width = 0.03,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Region"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2) +
  scale_fill_manual(
    breaks = names(BMR_cols),
    values = BMR_cols,
    guide = guide_legend(title = "Region", ncol = 1, order = 2)
  ) + aes(x = x, y = y)

# Format the plot
y_axis_expand_factor = 1.2
Figure_3A <- Figure_3A +
  theme_tree2() +
  scale_x_ggtree() + #set the x axis more reasonably.
  scale_y_continuous(
    limits = c(0, nrow(seq_metadata)*y_axis_expand_factor),
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    breaks = seq(2020, 2024, 1),
    limits = c(2019.80, 2025.15),
    expand = expansion(mult = c(0, 0))) +
  theme(
    legend.position = c(0,1/y_axis_expand_factor), legend.justification = c(0, 1),
    legend.direction = "vertical", legend.box = "horizontal",
    legend.background = element_blank(),
    
    legend.key = element_rect(fill = NA, colour = NA),
    legend.key.size = unit(0.25, 'cm'),
    legend.key.spacing = unit(0, 'cm'),
    
    legend.title = element_text(size = 8, face = "bold", margin = margin(t = 1, b = 1)),
    legend.text = element_text(size = 6, margin = margin(r = 0, l = 0)),
    legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
    
    axis.title = element_text(size = 8),
    axis.text = element_text(size = 6),
    axis.text.x = element_text(size = 6, vjust = 0),
    
    plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "pt"),
  )

# ###############################
# Sequence clustering analysis (only among our sequences)
# ###############################
# Compute pairwise sequence distance (in the units of time)
# -------------------------------
dist_matrix <- cophenetic(
  drop.tip(
    tree, 
    setdiff(tree$tip.label, seq_metadata %>% filter(source == "This study") %>% pull(seq_id))
  )
)

# Cluster sequences based on a (time) distance cutoff
# -------------------------------
# Clustering 
dist_cutoff <- (30/365)*2 # Differ by 30 days or fewer from the MRCA on average

clusters <- graph_from_adjacency_matrix(
  adjmatrix = (dist_matrix <= dist_cutoff),
  mode = "undirected",
  diag = FALSE) %>% 
  components

cluster_assignments <- clusters$membership

# For each cluster, check in the full tree if there are any sequences that are from outside of our cohort ...
# ... And the answer is "NO" :)
# -------------------------------
for(cluster_i in unique(cluster_assignments)) {
  cluster_i_tips <- names(cluster_assignments)[cluster_assignments == cluster_i]
  
  if(length(cluster_i_tips) > 1){
    sub_tree <- tree_subset(
      tree = tree,
      node = MRCA(tree, names(cluster_assignments)[cluster_assignments == cluster_i]),
      levels_back = 0
    )
    cluster_i_tips <- sub_tree$tip.label
  }
  
  seq_sources <- seq_metadata %>%
    filter(seq_id %in% cluster_i_tips) %>%
    pull(source)
  
  if (any(seq_sources != "This study")){
    print(sprintf("cluster %s contains GISAID public sequences!!!!!!!!!!!!!!!", cluster_i))
    print(cluster_i_tips)
  } else {
    print(sprintf("cluster %s contains sequences from our cohort only", cluster_i))
    print(cluster_i_tips)
  }
}

# Soft prune the time-calibrated phylogeny, ...
# to retain sequences from our cohort and their closest contextualising sequences only.
# Also, make soft_pruned_seq_metadata
# -------------------------------
# For each cluster, expand it to include its sister clade(s) by "levels_back" (1)
# The union set will be the set of tips to be retained in the pruned tree
levels_back = 1
tips_to_keep <- NULL
for(cluster_i in unique(cluster_assignments)) {
  expanded_cluster_i_tips <- tree_subset(
    tree = tree,
    node = MRCA(tree, names(cluster_assignments)[cluster_assignments == cluster_i]),
    levels_back = levels_back
  )$tip.label
  
  tips_to_keep <- c(tips_to_keep, expanded_cluster_i_tips)
}
tips_to_keep <- unique(tips_to_keep)

# Prune the tree to include only these tips
soft_pruned_tree <- drop.tip(tree, setdiff(tree$tip.label, tips_to_keep))

# Create soft_pruned_seq_metadata for the soft_pruned_tree
soft_pruned_seq_metadata <- seq_metadata %>% filter(seq_id %in% soft_pruned_tree$tip.label)

# Make cluster_metadata_soft_pruned_tree df for plotting Figure S3
# ----------------------------
# Plot the soft pruned tree to get data
soft_pruned_tree_plot <- ggtree(
  tr = soft_pruned_tree,
  mrsd = soft_pruned_seq_metadata %>% 
    pull(collection_date) %>% as.Date() %>% 
    sort(decreasing = TRUE) %>% head(1),
  ladderize = FALSE,
) %<+% soft_pruned_seq_metadata

soft_pruned_tree_data <- soft_pruned_tree_plot$data

cluster_metadata_soft_pruned_tree <- NULL
for(cluster_i in unique(cluster_assignments)) {
  # Tips that belong to this cluster
  cluster_i_tips <- names(cluster_assignments)[cluster_assignments == cluster_i]
  # Virus lineage
  cluster_i_major_lineage <- soft_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(major_lineage) %>% unique()
  # Cluster size
  cluster_i_size <- length(cluster_i_tips)
  # MRCA node for these tips in the pruned tree
  cluster_i_MRCA_node <- MRCA(soft_pruned_tree, cluster_i_tips)
  # x coordinate of MRCA node
  cluster_i_MRCA_x <- soft_pruned_tree_data %>% filter(node == cluster_i_MRCA_node) %>% pull(x)
  # y coordinate of MRCA node
  cluster_i_MRCA_y <- soft_pruned_tree_data %>% filter(node == cluster_i_MRCA_node) %>% pull(y)
  
  # Just in case there are sequences from outside of our cohort in cluster_i,
  # Extract the clade from the MRCA node and update tip labels in that clade
  cluster_i_tips = if(length(cluster_i_tips) > 1){
    extract.clade(soft_pruned_tree, cluster_i_MRCA_node)$tip.label
  } else {
    cluster_i_tips
  }
  
  # For tips in this clade, get their max x coordinate from the tree data (Most Recent Sample date)
  cluster_i_MRS_x <- soft_pruned_tree_data %>% filter(isTip, label %in% cluster_i_tips) %>% pull(x) %>% max(na.rm = TRUE)
  # Compute cluster timescale as the difference between the MRS x coordinate and the MRCA x coordinate
  cluster_i_timescale <- cluster_i_MRS_x - cluster_i_MRCA_x
  
  # Determine HH
  cluster_i_HH <- soft_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(family_id)
  # Determine first_HH_case_age_cat
  cluster_i_first_HH_case_age_cat <- first_HH_case_age_cat_dat %>% filter(family_id %in% cluster_i_HH) %>% pull(first_HH_case_age_cat) 
  # Determine if samples in cluster_i are from HH_with_complete_seq_dat
  cluster_i_HH_with_complete_seq_dat <- soft_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(HH_with_complete_seq_dat)
  
  # Keep the results in the list cluster_metadata_soft_pruned_tree
  cluster_metadata_soft_pruned_tree[[as.character(cluster_i)]] <- list(
    tips = cluster_i_tips,
    HH = cluster_i_HH,
    first_HH_case_age_cat = cluster_i_first_HH_case_age_cat,
    HH_with_complete_seq_dat = cluster_i_HH_with_complete_seq_dat,
    major_lineage = cluster_i_major_lineage,
    size = cluster_i_size,
    MRCA_node = cluster_i_MRCA_node,
    MRCA_x = cluster_i_MRCA_x,
    MRCA_y = cluster_i_MRCA_y,
    MRS_x = cluster_i_MRS_x,
    timescale = cluster_i_timescale
  )
}

# Make cluster_metadata_soft_pruned_tree into a df
cluster_metadata_soft_pruned_tree <- data.frame(
  cluster_id = names(cluster_metadata_soft_pruned_tree),
  assoc_HH = map_chr(cluster_metadata_soft_pruned_tree, function(x) paste(unique(pluck(x, "HH")), collapse = ", ")),
  first_HH_case_age_cat = map_chr(cluster_metadata_soft_pruned_tree, function(x) {first_HH_case_age_cat_vec <- unique(pluck(x, "first_HH_case_age_cat")); ifelse(length(first_HH_case_age_cat_vec)==1, as.character(first_HH_case_age_cat_vec), "Adult-first household")}),
  assoc_with_HH_with_complete_seq_dat = map_chr(cluster_metadata_soft_pruned_tree, function(x) ifelse(any(pluck(x, "HH_with_complete_seq_dat")), "Yes", "No")),
  major_lineage = map_chr(cluster_metadata_soft_pruned_tree, function(x) as.character(pluck(x, "major_lineage"))),
  size = map_dbl(cluster_metadata_soft_pruned_tree, "size"),
  MRCA_node = map_dbl(cluster_metadata_soft_pruned_tree, "MRCA_node"),
  MRCA_x = map_dbl(cluster_metadata_soft_pruned_tree, "MRCA_x"),
  MRCA_y = map_dbl(cluster_metadata_soft_pruned_tree, "MRCA_y"),
  MRS_x = map_dbl(cluster_metadata_soft_pruned_tree, "MRS_x"),
  timescale = map_dbl(cluster_metadata_soft_pruned_tree, "timescale")
) 

# Rename the clusters so that they appear sequential in the plot (top = smallest, bottom = largest)
cluster_metadata_soft_pruned_tree <- cluster_metadata_soft_pruned_tree %>% 
  arrange(desc(MRCA_y)) %>%
  mutate(
    cluster_id_ori = cluster_id,
    cluster_id = row_number(),
  )

# Recode the cluster id in cluster_assignments
mapping <- setNames(cluster_metadata_soft_pruned_tree$cluster_id, cluster_metadata_soft_pruned_tree$cluster_id_ori)
cluster_assignments <- data.frame(
  seq_id = names(cluster_assignments), 
  cluster_id = mapping[as.character(cluster_assignments)]
) %>% deframe()

# ###############################
# Plot Figure S3: Soft pruned time-calibrated phylogeny with sequence clusters highlighted
# ###############################
# Plot the base plot
# -------------------------------
Figure_S3 <- ggtree(
  tr = soft_pruned_tree,
  mrsd = soft_pruned_seq_metadata %>% 
    pull(collection_date) %>% as.Date() %>% 
    sort(decreasing = TRUE) %>% head(1),
  ladderize = FALSE,
  size = 0.2
) %<+% (
  soft_pruned_seq_metadata %>% 
    mutate(
      cluster_id = cluster_assignments[seq_id],
      col = ifelse(cluster_id %% 2 == 0, "blue", "red"), # blue for sequences in even clusters, and red for sequences in odd clusters
      fontface = ifelse(HH_with_complete_seq_dat, "bold", "plain")
    )
)

# Highlight our sequences with red or blue tips, align tip labels
# -------------------------------
label_offset <- 0.4
soft_pruned_tree_tip_df <- Figure_S3$data %>%
  filter(isTip) %>%
  mutate(label_x = max(Figure_S3$data$x, na.rm = TRUE) + label_offset)

Figure_S3 <- Figure_S3 + 
  geom_tiplab(
    mapping = aes(col = col, fontface = fontface),
    align = TRUE, linetype = NULL, linesize = 0.5,
    offset = 0.4,
    size = 2,
  ) +
  scale_colour_manual(
    values = c("blue" = "blue", "red" = "red"), 
    guide = "none"
  ) +
  geom_segment(
    data = soft_pruned_tree_tip_df,
    aes(x = x+0.01, xend = label_x, y = y, yend = y, colour = col),
    size = 0.5, linetype = "dotted", 
    inherit.aes = FALSE
  ) 

# For each sequence cluster, highlight the cluster with a transparent rectangle
# -------------------------------
Figure_S3 <- Figure_S3 + 
  geom_hilight(
    data = cluster_metadata_soft_pruned_tree %>% filter(cluster_id %% 2 == 0),
    mapping = aes(node = MRCA_node, linetype = assoc_with_HH_with_complete_seq_dat, alpha = assoc_with_HH_with_complete_seq_dat),
    fill = "blue", col = "blue", linewidth = 0.1, 
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none") +
  scale_alpha_manual(breaks = c("Yes", "No"), values = c(0.7, 0.3), guide = "none")

Figure_S3 <- Figure_S3 + 
  geom_hilight(
    data = cluster_metadata_soft_pruned_tree %>% filter(cluster_id %% 2 == 1),
    mapping = aes(node = MRCA_node, linetype = assoc_with_HH_with_complete_seq_dat, alpha = assoc_with_HH_with_complete_seq_dat),
    fill = "red", col = "red", linewidth = 0.1, 
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none") +
  scale_alpha_manual(breaks = c("Yes", "No"), values = c(0.7, 0.3), guide = "none")

# Label clusters with cluster ID
# -------------------------------
Figure_S3 <- Figure_S3 +
  geom_label(
    data = cluster_metadata_soft_pruned_tree %>% filter(cluster_id %% 2 == 0) %>% 
      mutate(fontface = ifelse(assoc_with_HH_with_complete_seq_dat == "Yes", "bold", "plain")),
    aes(x = 2024.8, y = MRCA_y, label = cluster_id, linetype = assoc_with_HH_with_complete_seq_dat, fontface = fontface),
    size = 2, color = "blue", fill = "white", 
    hjust = 0, vjust = 0.5,
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none")

Figure_S3 <- Figure_S3 +
  geom_label(
    data = cluster_metadata_soft_pruned_tree %>% filter(cluster_id %% 2 == 1) %>% 
      mutate(fontface = ifelse(assoc_with_HH_with_complete_seq_dat == "Yes", "bold", "plain")),
    aes(x = 2024.6, y = MRCA_y, label = cluster_id, linetype = assoc_with_HH_with_complete_seq_dat, fontface = fontface),
    size = 2, color = "red", fill = "white", 
    hjust = 0, vjust = 0.5,
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none")

# Add heatmaps to the plot
# -------------------------------
o <- 0.2 # heatmap offset: defined wrt to the tree's height
Figure_S3 <- gheatmap(
  p = Figure_S3,
  data = soft_pruned_seq_metadata %>% select(seq_id, major_lineage) %>% column_to_rownames(var = "seq_id"),
  offset = 3.8 + o*0, width = 0.05,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Major\nlineage"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(major_lineage_cols),
    values = major_lineage_cols,
    guide = guide_legend(title = "Major\nlineage", ncol = 1, order = 1)
  ) + aes(x = x, y = y)

Figure_S3 <- gheatmap(
  p = Figure_S3 + new_scale_fill(),
  data = soft_pruned_seq_metadata %>% select(seq_id, region) %>% column_to_rownames(var = "seq_id"),
  offset = 3.8 + o*1, width = 0.05,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Region"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(BMR_cols),
    values = BMR_cols,
    guide = guide_legend(title = "Region", nrow = 2, order = 2)
  ) + aes(x = x, y = y)

# Format the plot and legend
# -------------------------------
y_axis_expand_factor = 1.02
Figure_S3 <- Figure_S3 + 
  scale_x_ggtree() + 
  theme_tree2() + 
  scale_y_continuous(
    limits = c(0, nrow(soft_pruned_seq_metadata)*y_axis_expand_factor),
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    breaks = seq(2021.5, 2024.5, 1),
    limits = c(2021, 2028.9),
    expand = expansion(mult = c(0, 0))
  ) +
  theme(
    legend.position = c(0, 1/y_axis_expand_factor), legend.justification = c(0, 1),
    legend.direction = "vertical", legend.box = "vertical",
    
    legend.background = element_blank(),

    legend.key = element_rect(fill = NA, colour = NA),
    legend.key.size = unit(0.25, 'cm'),
    legend.key.spacing = unit(0, 'cm'),
    
    legend.title = element_text(size = 8, face = "bold", margin = margin(t = 1, b = 1)),
    legend.text = element_text(size = 6, margin = margin(r = 0, l = 0)),
    legend.margin = margin(t = 0, r = 0, b = 0, l = 0),

    axis.title = element_text(size = 8),
    axis.text = element_text(size = 6),
    axis.text.x = element_text(size = 6, vjust = 0),
    
    plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "pt"),
  )

# Save it to file
# -------------------------------
ggsave(filename = Figure_S3_file_png, device = "png",
       plot = Figure_S3,
       width = 16, height = 50, units = "cm", dpi = 300, bg = "white")

ggsave(filename = Figure_S3_file_svg, device = "svg",
       plot = Figure_S3,
       width = 16, height = 50, units = "cm", dpi = 300, bg = "white")

# ###############################
# Hard prune the time-calibrated phylogeny to retain only sequences from our cohort
# Also, make hard_hard_pruned_seq_metadata
# ###############################
# Hard prune the tree to retain only sequences from our cohort 
# -------------------------------
hard_pruned_tree <- drop.tip(
  tree, 
  setdiff(tree$tip.label, seq_metadata %>% filter(source == "This study") %>% pull(seq_id))
)

# Create hard_pruned_seq_metadata for the hard_pruned_tree
# -------------------------------
hard_pruned_seq_metadata <- seq_metadata %>% filter(seq_id %in% hard_pruned_tree$tip.label)
hard_pruned_seq_metadata <- left_join(
  hard_pruned_seq_metadata,
  data.frame(
    seq_id = names(cluster_assignments),
    cluster_id = as.vector(cluster_assignments)
  ),
  by = "seq_id"
)

# Make cluster_metadata_hard_pruned_tree df for plotting Figure 3B
# -------------------------------
# Plot the hard pruned tree to get data
hard_pruned_tree_plot <- ggtree(
  tr = hard_pruned_tree,
  mrsd = hard_pruned_seq_metadata %>% 
    pull(collection_date) %>% as.Date() %>% 
    sort(decreasing = T) %>% head(1),
  ladderize = F,
) %<+% hard_pruned_seq_metadata

hard_pruned_tree_data <- hard_pruned_tree_plot$data

cluster_metadata_hard_pruned_tree <- NULL
for(cluster_i in unique(cluster_assignments)) {
  # Tips that belong to this cluster
  cluster_i_tips <- names(cluster_assignments)[cluster_assignments == cluster_i]
  # Virus lineage
  cluster_i_major_lineage <- hard_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(major_lineage) %>% unique()
  # Cluster size
  cluster_i_size <- length(cluster_i_tips)
  # MRCA node for these tips in the hard_pruned tree
  cluster_i_MRCA_node <- MRCA(hard_pruned_tree, cluster_i_tips)
  # x coordinate of MRCA node
  cluster_i_MRCA_x <- hard_pruned_tree_data %>% filter(node == cluster_i_MRCA_node) %>% pull(x)
  # y coordinate of MRCA node
  cluster_i_MRCA_y <- hard_pruned_tree_data %>% filter(node == cluster_i_MRCA_node) %>% pull(y)
  
  # For these clade tips, get their max x coordinate from the tree data (Most Recent Sample date)
  cluster_i_MRS_x <- hard_pruned_tree_data %>% filter(isTip, label %in% cluster_i_tips) %>% pull(x) %>% max(na.rm = TRUE)
  # Compute timescale as the difference between the MRS x coordinate and the MRCA x coordinate
  cluster_i_timescale <- cluster_i_MRS_x - cluster_i_MRCA_x
  
  # Determine HH
  cluster_i_HH <- hard_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(family_id)
  # Determine first_HH_case_age_cat
  cluster_i_first_HH_case_age_cat <- first_HH_case_age_cat_dat %>% filter(family_id %in% cluster_i_HH) %>% pull(first_HH_case_age_cat) 
  # Determine if samples in cluster_i are from HH_with_complete_seq_dat
  cluster_i_HH_with_complete_seq_dat <- hard_pruned_tree_data %>% filter(label %in% cluster_i_tips) %>% pull(HH_with_complete_seq_dat)
  
  # Keep the results in the list cluster_metadata_hard_pruned_tree
  cluster_metadata_hard_pruned_tree[[as.character(cluster_i)]] <- list(
    tips = cluster_i_tips,
    HH = cluster_i_HH,
    first_HH_case_age_cat = cluster_i_first_HH_case_age_cat,
    HH_with_complete_seq_dat = cluster_i_HH_with_complete_seq_dat,
    major_lineage = cluster_i_major_lineage,
    size = cluster_i_size,
    MRCA_node = cluster_i_MRCA_node,
    MRCA_x = cluster_i_MRCA_x,
    MRCA_y = cluster_i_MRCA_y,
    MRS_x = cluster_i_MRS_x,
    timescale = cluster_i_timescale
  )
}

# Make cluster_metadata_hard_pruned_tree into a df
cluster_metadata_hard_pruned_tree <- data.frame(
  cluster_id = names(cluster_metadata_hard_pruned_tree) %>% as.integer(),
  assoc_HH = map_chr(cluster_metadata_hard_pruned_tree, function(x) paste(unique(pluck(x, "HH")), collapse = ", ")),
  first_HH_case_age_cat = map_chr(cluster_metadata_hard_pruned_tree, function(x) {first_HH_case_age_cat_vec <- unique(pluck(x, "first_HH_case_age_cat")); ifelse(length(first_HH_case_age_cat_vec)==1, as.character(first_HH_case_age_cat_vec), "Adult-first household")}),
  assoc_with_HH_with_complete_seq_dat = map_chr(cluster_metadata_hard_pruned_tree, function(x) ifelse(any(pluck(x, "HH_with_complete_seq_dat")), "Yes", "No")),
  major_lineage = map_chr(cluster_metadata_hard_pruned_tree, function(x) as.character(pluck(x, "major_lineage"))),
  size = map_dbl(cluster_metadata_hard_pruned_tree, "size"),
  MRCA_node = map_dbl(cluster_metadata_hard_pruned_tree, "MRCA_node"),
  MRCA_x = map_dbl(cluster_metadata_hard_pruned_tree, "MRCA_x"),
  MRCA_y = map_dbl(cluster_metadata_hard_pruned_tree, "MRCA_y"),
  MRS_x = map_dbl(cluster_metadata_hard_pruned_tree, "MRS_x"),
  timescale = map_dbl(cluster_metadata_hard_pruned_tree, "timescale")
)

# No need to rename "cluster_id"s anymore 
# to keep the IDs consistent with those in Figure S3

# ###############################
# Plot Figure 3B: hard_pruned time-calibrated phylogeny with sequence clusters highlighted
# ###############################
# Base plot
# -------------------------------
Figure_3B <- ggtree(
  tr = hard_pruned_tree,
  mrsd = hard_pruned_seq_metadata %>% 
    pull(collection_date) %>% as.Date() %>%
    sort(decreasing = TRUE) %>% head(1),
  ladderize = FALSE,
  size = 0.2
) %<+% (
  hard_pruned_seq_metadata %>% 
    mutate(
      cluster_id = cluster_assignments[seq_id],
      col = ifelse(cluster_id %% 2 == 0, "blue", "red"), # blue for even clusters, and red for odd clusters
      fontface = ifelse(HH_with_complete_seq_dat, "bold", "plain")
    )
)

# Highlight our sequences with red or blue tips, align tip labels
# -------------------------------
label_offset <- 0.4
hard_pruned_tree_tip_df <- Figure_3B$data %>%
  filter(isTip) %>%
  mutate(label_x = max(Figure_3B$data$x, na.rm = TRUE) + label_offset)

Figure_3B <- Figure_3B + 
  geom_tiplab(
    mapping = aes(col = col, fontface = fontface),
    align = TRUE, linetype = NULL, linesize = 0.5,
    offset = 0.4,
    size = 1.75,
  ) +
  scale_colour_manual(
    values = c("blue" = "blue", "red" = "red"), 
    guide = "none"
  ) +
  geom_segment(
    data = hard_pruned_tree_tip_df,
    aes(x = x+0.01, xend = label_x, y = y, yend = y, colour = col),
    size = 0.5, linetype = "dotted", 
    inherit.aes = FALSE
  ) 

# For each sequence cluster, highlight the cluster with a transparent rectangle (using geom_hilight)
# -------------------------------
Figure_3B <- Figure_3B + 
  geom_hilight(
    data = cluster_metadata_hard_pruned_tree %>% filter(cluster_id %% 2 == 0),
    mapping = aes(node = MRCA_node, linetype = assoc_with_HH_with_complete_seq_dat, alpha = assoc_with_HH_with_complete_seq_dat),
    fill = "blue", col = "blue", size = 0.1, type="rect", 
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none") +
  scale_alpha_manual(breaks = c("Yes", "No"), values = c(0.7, 0.3), guide = "none")

Figure_3B <- Figure_3B + 
  geom_hilight(
    data = cluster_metadata_hard_pruned_tree %>% filter(cluster_id %% 2 == 1),
    mapping = aes(node = MRCA_node, linetype = assoc_with_HH_with_complete_seq_dat, alpha = assoc_with_HH_with_complete_seq_dat),
    fill = "red", col = "red", linewidth = 0.1
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none") +
  scale_alpha_manual(breaks = c("Yes", "No"), values = c(0.7, 0.3), guide = "none")

# Label clusters with cluster ID
# -------------------------------
Figure_3B <- Figure_3B +
  geom_label(
    data = cluster_metadata_hard_pruned_tree %>% filter(cluster_id %% 2 == 0) %>% 
      mutate(fontface = ifelse(assoc_with_HH_with_complete_seq_dat == "Yes", "bold", "plain")),
    aes(x = 2024.8, y = MRCA_y, label = cluster_id, linetype = assoc_with_HH_with_complete_seq_dat, fontface = fontface),
    size = 2, color = "blue", fill = "white", 
    hjust = 0, vjust = 0.5,
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none")

Figure_3B <- Figure_3B +
  geom_label(
    data = cluster_metadata_hard_pruned_tree %>% filter(cluster_id %% 2 == 1) %>% 
      mutate(fontface = ifelse(assoc_with_HH_with_complete_seq_dat == "Yes", "bold", "plain")),
    aes(x = 2024.7, y = MRCA_y, label = cluster_id, linetype = assoc_with_HH_with_complete_seq_dat, fontface = fontface),
    size = 2, color = "red", fill = "white", 
    hjust = 0, vjust = 0.5,
  ) + 
  scale_linetype_manual(breaks = c("Yes", "No"), values = c("solid", "dashed"), guide = "none")

# Add heatmaps to the plot
# -------------------------------
base_offset <- 1.05
o <- 0.15 # heatmap offset: defined wrt to the tree's height
Figure_3B <- gheatmap(
  p = Figure_3B,
  data = hard_pruned_seq_metadata %>% select(seq_id, major_lineage) %>% column_to_rownames(var = "seq_id"),
  offset = base_offset + o*0, width = 0.04,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Major\nlineage"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(major_lineage_cols),
    values = major_lineage_cols,
    guide = guide_legend(title = "Major lineage", ncol = 1, order = 1)
  ) + aes(x = x)

Figure_3B <- gheatmap(
  p = Figure_3B + new_scale_fill(),
  data = hard_pruned_seq_metadata %>% select(seq_id, age_cat) %>% column_to_rownames(var = "seq_id"),
  offset = base_offset + o*1, width = 0.04,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Age\ncategory"), colnames_position = "top",
  colnames_angle = 90, hjust = 0, 
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(age_cat_cols),
    values = age_cat_cols,
    guide = guide_legend(title = "Age category", ncol = 1, order = 2)
  ) + aes(x = x)

Figure_3B <- gheatmap(
  p = Figure_3B + new_scale_fill(),
  data = hard_pruned_seq_metadata %>% select(seq_id, first_HH_case_age_cat) %>% column_to_rownames(var = "seq_id"),
  offset = base_offset + o*2, width = 0.04,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Household\ntype"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(HH_type_cols),
    values = HH_type_cols,
    guide = guide_legend(title = "Household type", ncol = 1, order = 3)
  ) + aes(x = x)

Figure_3B <- gheatmap(
  p = Figure_3B + new_scale_fill(),
  data = hard_pruned_seq_metadata %>% select(seq_id, overall_res_end_with_symp_severity) %>% column_to_rownames(var = "seq_id"),
  offset = base_offset + o*3, width = 0.04,
  color = NULL,
  colnames = TRUE, custom_column_labels = c("Symptom\nlevel"), colnames_position = "top",
  colnames_angle = 90, hjust = 0,
  font.size = 2
) +
  scale_fill_manual(
    breaks = names(overall_res_end_with_symp_severity_cols),
    values = overall_res_end_with_symp_severity_cols,
    labels = c(
      "Pos: no symptom data"= "No symptom data",
      "Pos: highly symptomatic" = "Highly symptomatic",
      "Pos: moderately symptomatic" = "Moderately symptomatic",
      "Pos: minimally/(a)symptomatic" = "Minimally/(a)symptomatic",
      "Neg" = "Negative",
      "Unconfirmed" = "NA"),
    guide = guide_legend(title = "Symptom level", ncol = 1, order = 4)
  ) + aes(x = x)

# Format the plot and legend
# -------------------------------
y_axis_expand_factor = 1.08
Figure_3B <- Figure_3B + 
  scale_x_ggtree() +
  theme_tree2() + 
  scale_y_continuous(
    limits = c(0, nrow(hard_pruned_seq_metadata)*y_axis_expand_factor),
    expand = c(0, 0)
  ) +
  scale_x_continuous(
    breaks = seq(2021.5, 2024.5, 1),
    limits = c(2021, 2026.35),
    expand = expansion(mult = c(0, 0))
  ) +
  theme(
    legend.position = c(0, 1/y_axis_expand_factor), legend.justification = c(0, 1),
    legend.direction = "vertical", legend.box = "vertical",

    legend.background = element_blank(),
    
    legend.key = element_rect(fill = NA, colour = NA),
    legend.key.size = unit(0.25, 'cm'),
    legend.key.spacing = unit(0, 'cm'),
    
    legend.title = element_text(size = 8, face = "bold", margin = margin(t = 1, b = 1)),
    legend.text = element_text(size = 6, margin = margin(r = 0, l = 0)),
    legend.margin = margin(t = 0, r = 0, b = 0, l = 0),
    
    axis.title = element_text(size = 8),
    axis.text = element_text(size = 6),
    axis.text.x = element_text(size = 6, vjust = 0),
    
    plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "pt"),
  )

# ###############################
# Plot Figure 3C: cluster size
# ###############################
Figure_3C <- ggplot(data = cluster_metadata_hard_pruned_tree) +
  geom_histogram(aes(x = size, fill = first_HH_case_age_cat), binwidth = 1, color = NA, alpha = 0.7) + # use 'position = "identity"' to overlay filled histograms if you want
  scale_x_continuous(
    breaks = seq(0, 8, 1),
    expand = c(0,0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 40, 10),
    expand = c(0,0)) + 
  scale_fill_manual(
    name = "Household type", 
    breaks = names(HH_type_cols),
    values = HH_type_cols
  ) +
  labs(
    x = "Cluster size",
    y = "Count",
    title = "Cluster sizes"
  ) +
  theme_bw() + my_theme + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

# ###############################
# Plot Figure 3D: Distribution of transmission cluster timescales (i.e., subtree heights)
# ###############################
Figure_3D <- ggplot(data = cluster_metadata_hard_pruned_tree) +
  geom_histogram(aes(x = timescale*365, fill = first_HH_case_age_cat), binwidth = 2, color = NA, alpha = 0.7) +
  scale_x_continuous(
    breaks = seq(0, 30, 5),
    expand = c(0,0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 50, 10),
    expand = c(0,0)) + #scale_y_break(c(10, 40), expand = F) + 
  scale_fill_manual(
    breaks = names(HH_type_cols),
    values = HH_type_cols,
    guide = "none"
  ) + 
  labs(
    x = "Subtree height (days)",
    y = "Count",
    title = "Cluster timescales"
  ) +
  theme_bw() + my_theme + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

# ###############################
# Plot Figure S4 and 5E: Family-cluster association
# ###############################
# Create a contingency table of families and clusters.
# -------------------------------
family_cluster_df <- hard_pruned_seq_metadata %>%
  filter(seq_id %in% names(cluster_assignments)) %>%
  mutate(cluster_id = cluster_assignments[seq_id]) %>%
  group_by(family_id, HH_with_complete_seq_dat, cluster_id) %>%
  summarise(count = n()) %>% 
  ungroup()

# Identify clusters with sequences from multiple families
# -------------------------------
clusters_with_multi_families <- family_cluster_df %>%
  group_by(cluster_id) %>%
  summarise(num_fams = n_distinct(family_id)) %>% 
  ungroup() %>%
  filter(num_fams > 1) %>%
  pull(cluster_id) %>% as.character()

clusters_with_multi_families
# [1] "20" "54" "56"

# Identify families that are present in multiple clusters
# -------------------------------
families_with_multi_clusters <- family_cluster_df %>%
  group_by(family_id) %>%
  summarise(num_clusters = n_distinct(cluster_id)) %>% 
  ungroup() %>%
  filter(num_clusters > 1) %>%
  pull(family_id) %>% as.character()

families_with_multi_clusters
# [1] "F002" "F006" "F008" "F023" "F024" "F026" "F029" "F030" "F031" "F035" "F047" "F054" "F056" "F059"

# Plot Figure S4: full matrix and save it to file
# -------------------------------
Figure_S4 <- family_cluster_df %>% 
  ggplot(aes(x = factor(cluster_id), y = family_id)) +
  geom_tile(aes(fill = count, linetype = HH_with_complete_seq_dat), col = "black") +
  scale_fill_viridis_c(option = "plasma", direction = -1, name = "Count", ) +
  scale_linetype_manual(breaks = c("TRUE", "FALSE"), values = c("solid", "dashed"), guide = "none") +
  labs(
    x = "Cluster ID",
    y = "Family ID",
    title = "Family-cluster association"
  ) +
  theme_minimal() + my_theme + 
  theme(
    legend.position = c(0, 1), legend.justification = c(0, 1),
    legend.direction = "horizontal", legend.box = "vertical",

    axis.text.x = element_text(
      size = 6, angle = 90, vjust = 0.5, hjust = 1,
      colour = ifelse(family_cluster_df$cluster_id %>% factor %>% levels %in% clusters_with_multi_families, "red", "grey30")
    ),
    axis.text.y = element_text(
      size = 6, angle = 0,
      colour = ifelse(family_cluster_df$family_id %>% factor %>% levels %in% families_with_multi_clusters, "red", "grey30")
    ),
  ) +
  guides(fill = guide_colorbar(title.position = "top"))

# Save Figure_S4 to file
ggsave(filename = Figure_S4_file_png, device = "png",
       plot = Figure_S4,
       width = 16, height = 16, units = "cm", dpi = 300, bg = "white")

ggsave(filename = Figure_S4_file_svg, device = "svg",
       plot = Figure_S4,
       width = 16, height = 16, units = "cm", dpi = 300, bg = "white")

# Plot Figure 3E: focusing on families with sequences forming multiple clusters, and...
# ...clusters containing sequences from multiple families 
# -------------------------------
Figure_3E <- Figure_S4

Figure_3E$data <- family_cluster_df %>% 
  filter(family_id %in% families_with_multi_clusters | cluster_id %in% clusters_with_multi_families)

Figure_3E <- Figure_3E + 
  scale_fill_viridis_c(option = "plasma", direction = -1, name = "Count", limit = c(1, 7)) +
  theme(
    axis.text.x = element_text(
      size = 6, angle = 90, vjust = 0.5, hjust = 1, 
      colour = ifelse(Figure_3E$data$cluster_id %>% factor %>% levels %in% clusters_with_multi_families, "red", "grey30")
    ),
    axis.text.y = element_text(
      size = 6, angle = 0, 
      colour = ifelse(Figure_3E$data$family_id %>% factor %>% levels %in% families_with_multi_clusters, "red", "grey30")
    ),
  )

# Combine the plots to make Figure 3 and save it to file
# --------------------
Figure_3C_3D_3E <- plot_grid(
  Figure_3C,
  Figure_3D, 
  Figure_3E,
  labels = c("C)", "D)", "E)"), label_size = 8, 
  label_x = 0, label_y = 1, hjust = 0, vjust = 1,
  nrow = 1, align = "h", axis = "tb", rel_widths = c(0.8, 1.2, 1.6)
) 

Figure_3 <- plot_grid(
  Figure_3A,
  Figure_3B,
  Figure_3C_3D_3E, 
  labels = c("A)", "B)", ""), label_size = 8,
  label_x = 0, label_y = 1, hjust = 0, vjust = 1,
  nrow = 3, 
  align = "v", axis = "lr", 
  rel_heights = c(1, 3.5, 1)
)

# Save Figure_3 to file
# -------------------------------
ggsave(filename = Figure_3_file_png, device = "png",
       plot = Figure_3,
       width = 16, height = 24, units = "cm", dpi = 300, bg = "white")

ggsave(filename = Figure_3_file_svg, device = "svg",
       plot = Figure_3,
       width = 16, height = 24, units = "cm", dpi = 300, bg = "white")

# ###############################
# Generate Table S9: sequence clustering results
# ###############################
# Generate the table
# -------------------------------
Table_S9 <- cluster_metadata_hard_pruned_tree %>% 
  select(cluster_id,
         assoc_HH, first_HH_case_age_cat, assoc_with_HH_with_complete_seq_dat,
         major_lineage,
         size,
         MRCA_x,
         MRS_x,
         timescale) %>%
  mutate(
    timescale_days = timescale * 365
  ) %>%
  rename(MRCA_date = MRCA_x, MRS_date = MRS_x, timescale_years = timescale) 

Table_S9 <- left_join(
  Table_S9,
  data.frame(cluster_id = cluster_assignments) %>% 
    rownames_to_column("seq_id") %>% 
    group_by(cluster_id) %>%
    summarise(
      seq_members = paste(seq_id, collapse = "; ")
    ) %>% ungroup(),
  by = "cluster_id"
) %>%
  relocate(seq_members, .after = cluster_id) %>%
  arrange(cluster_id)

# Save it to file
# -------------------------------
write_tsv(Table_S9, Table_S9_file)

# ###############################
# Some sequence stats
# and miscellaneous info
# ###############################
# Sequences are from 54 households, 27 child-first and 27 adult-first households
# -------------------------------
seq_metadata %>% 
  select(family_id, first_HH_case_age_cat) %>% unique() %>% pull(first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
# .
# Child-first household Adult-first household                  <NA>                   Sum 
#                    27                    27                     1                    55 
# NA == unknown HHs of public sequences 

# Sequences are from 63 children and 65 adults, 
# 43 of which were from child-first households, and 85 were from adult-first households
# -------------------------------
hard_pruned_seq_metadata %>% 
  select(age_cat, first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
#        first_HH_case_age_cat
# age_cat Child-first household Adult-first household Sum
#   Child                    28                    35  63
#   Adult                    15                    50  65
#   Sum                      43                    85 128

# 72 unique cluster-family combinations 
# -------------------------------
hard_pruned_seq_metadata %>% select(family_id, cluster_id) %>% unique() %>% nrow
# [1] 72

# Singleton clusters: 37 in total
# 26 are associated with child patients with 13 from HH_with_complete_seq_dat, 
# 11 are associated with adult patients with 3 from HH_with_complete_seq_dat
# -------------------------------
hard_pruned_seq_metadata %>%
  filter(cluster_id %in% (cluster_metadata_hard_pruned_tree %>% filter(size == 1) %>% pull(cluster_id))) %>%
  select(age_cat, HH_with_complete_seq_dat) %>% 
  table(useNA = "ifany") %>% addmargins()
#        HH_with_complete_seq_dat
# age_cat FALSE TRUE Sum
#   Child    13   13  26
#   Adult     8    3  11
#   Sum      21   16  37

# Cluster count by major lineage
# -------------------------------
hard_pruned_seq_metadata %>%
  select(cluster_id, major_lineage) %>% unique %>% pull(major_lineage) %>% 
  table(useNA = "ifany") %>% addmargins()
# .
#     BA.5    BA.2.75        XBB        XBL XBB or XBL    BA.2.86     Others        Sum 
#        3         17         31          1          0         17          0         69 

# Clusters with sequences from multiple families
# -------------------------------
clusters_with_multi_families
# [1] "20" "54" "56"

# Families with multiple clusters
# -------------------------------
families_with_multi_clusters
# [1] "F002" "F006" "F008" "F023" "F024" "F026" "F029" "F030" "F031" "F035" "F047" "F054" "F056" "F059"

# Families with sequences forming multiple clusters by household type: ALL households
# -------------------------------
seq_metadata %>% 
  select(family_id, first_HH_case_age_cat) %>% unique() %>%
  filter(family_id %in% families_with_multi_clusters) %>%
  pull(first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
# .
# Child-first household Adult-first household                   Sum 
#                     2                    12                    14 

# Families with sequences forming multiple clusters by household type: households with complete seq data only
# -------------------------------
seq_metadata %>% 
  filter(HH_with_complete_seq_dat) %>% 
  select(family_id, first_HH_case_age_cat) %>% unique() %>% 
  filter(family_id %in% families_with_multi_clusters) %>% 
  pull(first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
# .
# Child-first household Adult-first household                   Sum 
#                     0                     5                     5

# ###############################
# ###############################
# Identify factors associated with clustering features 
# using the FULL DATA SET (both "HH_with_complete_seq_dat" == T or F)
# - singleton
# - cluster size
# - cluster timescale
# ###############################
# ###############################

# ###############################
# Singleton analysis
# ###############################
# Prepare data for model fitting (N = 128)
# -------------------------------
singleton_data_full <- left_join(
    hard_pruned_seq_metadata %>%
      mutate(
        major_lineage = ifelse(major_lineage %in% c("XBB", "XBL"), "XBB or XBL", as.character(major_lineage))
        ),
    cluster_metadata_hard_pruned_tree %>% 
      mutate(
        singleton = case_when(
          size == 1 ~ "1",
          TRUE ~ "0"
        )
      ) %>% select(-c(first_HH_case_age_cat, major_lineage)), #hard_pruned_seq_metadata already has first_HH_case_age_cat and major_lineage
    by = "cluster_id"
  ) %>% 
  select(seq_id, singleton, age_cat, first_HH_case_age_cat, sex, major_lineage, overall_res_end_with_symp_severity, HH_with_complete_seq_dat, family_id) %>%
  mutate(singleton = factor(singleton))

nrow(singleton_data_full)
# [1] 128

# Lineage dist
singleton_data_full %>% 
  select(singleton, major_lineage) %>% 
  table(useNA = "ifany") %>% addmargins()
#          major_lineage
# singleton BA.2.75 BA.2.86 BA.5 XBB or XBL Sum
#       0        20      27    3         41  91
#       1        10       7    2         18  37
#       Sum      30      34    5         59 128

# Number of HHs by HH type
singleton_data_full %>%
  select(family_id, first_HH_case_age_cat) %>% unique() %>%
  select(first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
# first_HH_case_age_cat
# Child-first household Adult-first household                   Sum 
#                    27                    27                    54 

# Number of singletons by HH type
singleton_data_full %>% 
  select(first_HH_case_age_cat, singleton) %>%
  table(useNA = "ifany") %>% addmargins()
#                        singleton
# first_HH_case_age_cat     0   1 Sum
#   Child-first household  22  21  43
#   Adult-first household  69  16  85
#   Sum                    91  37 128

# Number of HHs by HH type and singleton %
singleton_data_full %>% 
  mutate(singleton = ifelse(singleton=="1",1,0)) %>%
  group_by(family_id) %>%
  summarise(
    first_HH_case_age_cat = unique(first_HH_case_age_cat),
    n_seqs = n(),
    n_singletons = sum(singleton),
    p_singletons = n_singletons/n_seqs*100,
    .groups = "drop"
  ) %>% 
  select(first_HH_case_age_cat, p_singletons) %>% 
  table(useNA = "ifany") %>% addmargins()
#                        p_singletons
# first_HH_case_age_cat    0 16.6666666666667 25 33.3333333333333 50 60 100 Sum
#   Child-first household  9                0  0                0  1  1  16  27
#   Adult-first household 15                1  1                5  0  0   5  27
#   Sum                   24                1  1                5  1  1  21  54

# Model fitting + stepwise BIC-based model selection
# -------------------------------
singleton_prob_mdl_reduced <- buildmer(
  singleton ~ (age_cat * first_HH_case_age_cat + sex + major_lineage + overall_res_end_with_symp_severity) + (1 | family_id),
  data = singleton_data_full,
  family = binomial,
  buildmerControl = buildmerControl(
    include = ~ (1 | family_id),
    direction = "backward",
    crit = "BIC",
    singular.ok = T,
    args = list(
      control = glmerControl(
        optimizer = "bobyqa",
        optCtrl = list(maxfun = 2e5)
      ) # end glmerControl
    ) # end args list
  ) # end buildmerControl
) # end buildmer

# Examine the reduced model
# -------------------------------
summary(singleton_prob_mdl_reduced@model)
# Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
#  Family: binomial  ( logit )
# Formula: singleton ~ 1 + first_HH_case_age_cat + (1 | family_id)
#    Data: singleton_data_full
# Control: structure(list(optimizer = c("bobyqa", "bobyqa"), restart_edge = FALSE,      boundary.tol = 1e-05, calc.derivs = NULL, use.last.params = FALSE,  
#     checkControl = list(autoscale = NULL, check.nobs.vs.rankZ = "ignore",          check.nobs.vs.nlev = "stop", check.nlev.gtreq.5 = "ignore",  
#         check.nlev.gtr.1 = "stop", check.nobs.vs.nRE = "stop",          check.rankX = "message+drop.cols", check.scaleX = "warning",  
#         check.formula.LHS = "stop", check.response.not.const = "stop"),      checkConv = list(check.conv.nobsmax = 10000, check.conv.nparmax = 20,  
#         check.conv.grad = list(action = "warning", tol = 0.002,              relTol = NULL), check.conv.singular = list(action = "message",  
#             tol = 1e-04), check.conv.hess = list(action = "warning",              tol = 1e-06)), optCtrl = list(maxfun = 2e+05), tolPwrss = 1e-07,  
#     compDev = TRUE, nAGQ0initStep = TRUE), class = c("glmerControl",  "merControl"))
# 
#       AIC       BIC    logLik -2*log(L)  df.resid 
#     139.2     147.7     -66.6     133.2       125 
# 
# Scaled residuals: 
#     Min      1Q  Median      3Q     Max 
# -1.2374 -0.4284 -0.2347  0.4829  2.3623 
# 
# Random effects:
#  Groups    Name        Variance Std.Dev.
#  family_id (Intercept) 4.815    2.194   
# Number of obs: 128, groups:  family_id, 54
# 
# Fixed effects:
#                                            Estimate Std. Error z value Pr(>|z|)  
# (Intercept)                                  0.5451     0.7667   0.711   0.4771  
# first_HH_case_age_catAdult-first household  -2.6892     1.2353  -2.177   0.0295 *
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#             (Intr)
# fr_HH___A-h -0.822

icc(singleton_prob_mdl_reduced@model)
# # Intraclass Correlation Coefficient
# 
#     Adjusted ICC: 0.594
#   Unadjusted ICC: 0.495

car::Anova(singleton_prob_mdl_reduced@model)
# Analysis of Deviance Table (Type II Wald chisquare tests)
# 
# Response: singleton
#                        Chisq Df Pr(>Chisq)  
# first_HH_case_age_cat 4.7391  1    0.02948 *
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Estimate singleton odds ratio between "Child-first household" VS "Adult-first household" based on the reduced model
# -------------------------------
emmeans(
  singleton_prob_mdl_reduced@model, 
  pairwise ~ first_HH_case_age_cat, 
  type = "response",
) %>% summary(infer = c(T, T)) %>%
  pluck("contrasts") %>% as.data.frame()
#  contrast                                          odds.ratio       SE  df asymp.LCL asymp.UCL null z.ratio p.value
#  (Child-first household) / (Adult-first household)   14.71969 18.18323 Inf  1.307403   165.725    1   2.177  0.0295
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the log odds ratio scale 
# Tests are performed on the log odds ratio scale 

# Estimate singleton rates for "Child-first household" VS "Adult-first household" based on the reduced model
# -------------------------------
emmeans(
  singleton_prob_mdl_reduced@model, 
   ~ first_HH_case_age_cat, 
  type = "response", # "weights" arg doesn't matter as the model contains only 1 fixed effect
 ) %>% summary(infer = c(T, T)) %>% as.data.frame() #%>%
#   mutate(
#     prob = round(prob * 100, 2),
#     asymp.LCL = round(asymp.LCL * 100, 2),
#     asymp.UCL = round(asymp.UCL * 100, 2),
#   )
#  first_HH_case_age_cat      prob         SE  df  asymp.LCL asymp.UCL null z.ratio p.value
#  Child-first household 0.6329919 0.17811503 Inf 0.27735194 0.8857234  0.5   0.711  0.4771
#  Adult-first household 0.1048827 0.07001955 Inf 0.02644474 0.3357422  0.5  -2.875  0.0040
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the logit scale 
# Tests are performed on the logit scale 

# ###############################
# Cluster size analysis
# ###############################
# Compute some basic stats
# -------------------------------
cluster_metadata_hard_pruned_tree %>% 
  select(major_lineage, size) %>% 
  table(useNA = "ifany") %>% addmargins()
#              size
# major_lineage  1  2  3  4  5  7 Sum
#       BA.2.75 10  4  1  1  1  0  17
#       BA.2.86  7  5  3  2  0  0  17
#       BA.5     2  0  1  0  0  0   3
#       XBB     18  7  3  1  1  1  31
#       XBL      0  1  0  0  0  0   1
#       Sum     37 17  8  4  2  1  69

# Recode major lineage
cluster_metadata_hard_pruned_tree <- cluster_metadata_hard_pruned_tree %>% 
  mutate(
    major_lineage_ori = major_lineage,
    major_lineage = ifelse(major_lineage %in% c("XBB", "XBL"), "XBB or XBL", as.character(major_lineage))
  ) 

cluster_metadata_hard_pruned_tree %>%
  select(major_lineage, size) %>% 
  table(useNA = "ifany") %>% addmargins()
#              size
# major_lineage  1  2  3  4  5  7 Sum
#    BA.2.75    10  4  1  1  1  0  17
#    BA.2.86     7  5  3  2  0  0  17
#    BA.5        2  0  1  0  0  0   3
#    XBB or XBL 18  8  3  1  1  1  32
#    Sum        37 17  8  4  2  1  69

cluster_metadata_hard_pruned_tree$size %>% summary
#  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 1.000   1.000   1.000   1.855   2.000   7.000 

cluster_metadata_hard_pruned_tree$size %>% sd
# 1.228047
# Notice that the cluster size dist is slightly underdisperse!

cluster_metadata_hard_pruned_tree %>% count(assoc_HH) %>% rename(HH_cluster_count = n) %>% 
  select(HH_cluster_count) %>% 
  table(useNA = "ifany") %>% addmargins()
# HH_cluster_count
#   1   2   3   4 Sum 
#  40  11   1   1  53 

# Model fitting + stepwise BIC-based model selection
# -------------------------------
# POISSON REGRESSION--which isn't quite suitable for underdispersed count data
cluster_size_pois_mdl_full_poisson <- glm(size ~ first_HH_case_age_cat * major_lineage, family = poisson, data = cluster_metadata_hard_pruned_tree)
cluster_size_pois_mdl_reduced_poisson <- step(cluster_size_pois_mdl_full_poisson, k = log(nrow(cluster_metadata_hard_pruned_tree)))
summary(cluster_size_pois_mdl_reduced_poisson)
# 
# Call:
# glm(formula = size ~ first_HH_case_age_cat, family = poisson, 
#     data = cluster_metadata_hard_pruned_tree)
# 
# Coefficients:
#                                            Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                  0.7655     0.1078   7.099 1.26e-12 ***
# first_HH_case_age_catChild-first household  -0.3951     0.1882  -2.099   0.0358 *  
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# (Dispersion parameter for poisson family taken to be 1)
# 
#     Null deviance: 45.472  on 68  degrees of freedom
# Residual deviance: 40.888  on 67  degrees of freedom
# AIC: 211.09
# 
# Number of Fisher Scoring iterations: 5

car::Anova(cluster_size_pois_mdl_reduced_poisson)
# Analysis of Deviance Table (Type II tests)
# 
# Response: size
#                       LR Chisq Df Pr(>Chisq)  
# first_HH_case_age_cat   4.5834  1    0.03228 *
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

deviance(cluster_size_pois_mdl_reduced_poisson) / df.residual(cluster_size_pois_mdl_reduced_poisson)
# [1] 0.6102754

# CONWAY-MAXWELL-POISSON REGRESSION--which is more suitable for underdispersed count data
cluster_size_pois_mdl_full_compois <- glmmTMB(
  size ~ first_HH_case_age_cat * major_lineage,
  family = compois(),
  data = cluster_metadata_hard_pruned_tree
)
cluster_size_pois_mdl_reduced_compois <- step(cluster_size_pois_mdl_full_compois, k = log(nrow(cluster_metadata_hard_pruned_tree)))
summary(cluster_size_pois_mdl_reduced_compois)
#  Family: compois  ( log )
# Formula:          size ~ first_HH_case_age_cat
# Data: cluster_metadata_hard_pruned_tree
# 
#       AIC       BIC    logLik -2*log(L)  df.resid 
#     204.5     211.2     -99.3     198.5        66 
# 
# 
# Dispersion parameter for compois family (): 0.512 
# 
# Conditional model:
#                                            Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                  0.7655     0.0821   9.323  < 2e-16 ***
# first_HH_case_age_catChild-first household  -0.3951     0.1469  -2.690  0.00713 ** 
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

sigma(cluster_size_pois_mdl_reduced_compois)
# [1] 0.5115143 # This is equivalent to nu = 1/0.5115143 = 1.95498, confirming underdispersion!!!

car::Anova(cluster_size_pois_mdl_reduced_compois)
# Analysis of Deviance Table (Type II Wald chisquare tests)
# 
# Response: size
#                        Chisq Df Pr(>Chisq)   
# first_HH_case_age_cat 7.2388  1   0.007135 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# And yes, CONWAY-MAXWELL-POISSON REGRESSION is our winner
BIC(cluster_size_pois_mdl_reduced_compois, cluster_size_pois_mdl_reduced_poisson)
#                                       df      BIC
# cluster_size_pois_mdl_reduced_compois  3 211.2361 # This is our winner!
# cluster_size_pois_mdl_reduced_poisson  2 215.5562

# Estimate the rate ratio
# ------------------------------------
emmeans(
  cluster_size_pois_mdl_reduced_compois, 
  pairwise ~ first_HH_case_age_cat, 
  type = "response"
) %>% summary(infer = c(T, T)) %>%
  pluck("contrasts") %>% as.data.frame()
#  contrast                                             ratio        SE  df asymp.LCL asymp.UCL null z.ratio p.value
#  (Adult-first household) / (Child-first household) 1.484524 0.2179995 Inf  1.113243  1.979632    1   2.690  0.0071
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the log scale 
# Tests are performed on the log scale 

# Estimate mean cluster sizes 
# ------------------------------------
emmeans(
  cluster_size_pois_mdl_reduced_compois, 
  ~ first_HH_case_age_cat, 
  type = "response"
) %>% summary(infer = c(T, T)) %>% as.data.frame()
#  first_HH_case_age_cat response        SE  df asymp.LCL asymp.UCL null z.ratio p.value
#  Adult-first household 2.150000 0.1765217 Inf  1.830426  2.525368    1   9.323 <0.0001
#  Child-first household 1.448276 0.1763299 Inf  1.140817  1.838596    1   3.042  0.0023
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the log scale 
# Tests are performed on the log scale 

# ###############################
# Cluster timescale analysis
# ###############################
# Prepare data for model fitting
# -------------------------------
cluster_timescale_df <- cluster_metadata_hard_pruned_tree %>% 
  select(timescale, first_HH_case_age_cat, major_lineage, assoc_with_HH_with_complete_seq_dat) %>%
  mutate(timescale = timescale*365)

nrow(cluster_timescale_df)
# [1] 69

# Compute some basic stats
# -------------------------------
cluster_timescale_df$timescale %>% table %>% cumsum
#                0 1.27604000001497 1.70747000000461 2.54478000004838 2.89773499994567 3.78833500002088 4.00003499998434  5.1800800000342  7.2098450000135 
#               48               49               50               51               52               53               54               55               56 
#  7.6704750000124 10.1480949999814 10.6039799999508 12.1738449999293 17.0097300000441 17.0637499999907 17.2495350000611 18.0018000000291 18.2047400000147 
#               57               58               59               60               61               62               63               64               65 
# 19.7308050000208 20.4005800000311 25.0371749999852 26.9651050000141 
#               66               67               68               69 

summary(cluster_timescale_df$timescale)
#  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 0.000   0.000   0.000   3.607   2.898  26.965 

sd(cluster_timescale_df$timescale)
# [1] 7.015171

sum(cluster_timescale_df$timescale <= 14)
# [1] 60

sum(cluster_timescale_df$timescale <= 21)
# [1] 67

sum(cluster_timescale_df$timescale <= 28)
# [1] 69

cluster_timescale_df %>% 
  group_by(first_HH_case_age_cat) %>%
  summarise(
    n = n(),
    mean_timescale = mean(timescale),
    med_timescale = median(timescale),
  )
#   first_HH_case_age_cat     n mean_timescale med_timescale
#   <chr>                 <int>          <dbl>         <dbl>
# 1 Adult-first household    40           4.15             0
# 2 Child-first household    29           2.86             0

cluster_timescale_df %>% 
  filter(timescale > 0) %>% 
  group_by(first_HH_case_age_cat) %>%
  summarise(
    n = n(),
    mean_timescale = mean(timescale),
    med_timescale = median(timescale),
  )
#   first_HH_case_age_cat     n mean_timescale med_timescale
#   <chr>                 <int>          <dbl>         <dbl>
# 1 Adult-first household    15           11.1          12.2
# 2 Child-first household     6           13.8          10.4

# Model fitting + stepwise BIC-based model selection
# -------------------------------
# We noticed from the previous section that only a few HHs have > 1 cluster
# So we won't fit a mixed-effects model for this either
# We would go fixed-effects only generalized additive models (to account for zero inflation)

cluster_timescale_mdl_full <- gamlss(timescale ~ first_HH_case_age_cat * major_lineage, data = cluster_timescale_df, family = ZAGA)
cluster_timescale_mdl_reduced <- step(cluster_timescale_mdl_full, k = log(nrow(cluster_timescale_df)))

# Examine the reduced model
summary(cluster_timescale_mdl_reduced)
# ******************************************************************
# Family:  c("ZAGA", "Zero Adjusted GA") 
# 
# Call:  gamlss(formula = timescale ~ 1, family = ZAGA, data = cluster_timescale_df) 
# 
# Fitting method: RS() 
# 
# ------------------------------------------------------------------
# Mu link function:  log
# Mu Coefficients:
#             Estimate Std. Error t value Pr(>|t|)    
# (Intercept)   2.4724     0.1674   14.77   <2e-16 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
# Sigma link function:  log
# Sigma Coefficients:
#             Estimate Std. Error t value Pr(>|t|)  
# (Intercept)  -0.2651     0.1418   -1.87   0.0659 .
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
# Nu link function:  logit 
# Nu Coefficients:
#             Estimate Std. Error t value Pr(>|t|)   
# (Intercept)   0.8267     0.2616    3.16  0.00238 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
# No. of observations in the fit:  69 
# Degrees of Freedom for the fit:  3
#       Residual Deg. of Freedom:  66 
#                       at cycle:  2 
#  
# Global Deviance:     227.6036 
#             AIC:     233.6036 
#             SBC:     240.3059 
# ******************************************************************

# Estimate zero adjusted cluster_timescale
# -------------------------------
emmeans(cluster_timescale_mdl_reduced, ~ 1, type = "response") %>% as.data.frame() %>%
  mutate(
    response = round(response, 2),
    asymp.LCL = round(asymp.LCL, 2),
    asymp.UCL = round(asymp.UCL, 2)
  )
#         1 response       SE  df asymp.LCL asymp.UCL
# 1 overall    11.85 1.983746 Inf      8.54     16.45

# ###############################
# ###############################
# Identify factors associated with clustering features: the SENSITIVITY ANALYSIS
# using the "HH_with_complete_seq_dat == T" DATA SET
# ###############################
# ###############################

# ###############################
# Singleton analysis
# ###############################
# Prepare data for model fitting (N = 65)
# -------------------------------
singleton_data_HH_with_complete_seq_only <- singleton_data_full %>% filter(HH_with_complete_seq_dat == T)

nrow(singleton_data_HH_with_complete_seq_only)
# [1] 65

# Lineage dist
singleton_data_HH_with_complete_seq_only %>% 
  select(singleton, major_lineage) %>% 
  table(useNA = "ifany") %>% addmargins()
#          major_lineage
# singleton BA.2.75 BA.2.86 BA.5 XBB or XBL Sum
#       0        12      17    0         20  49
#       1         4       4    1          7  16
#       Sum      16      21    1         27  65

# Number of HHs by HH type
singleton_data_HH_with_complete_seq_only %>%
  select(family_id, first_HH_case_age_cat) %>% unique() %>%
  select(first_HH_case_age_cat) %>% 
  table(useNA = "ifany") %>% addmargins()
# first_HH_case_age_cat
# Child-first household Adult-first household                   Sum 
#                    18                    11                    29

# Number of singletons by HH type
singleton_data_HH_with_complete_seq_only %>% 
  select(first_HH_case_age_cat, singleton) %>%
  table(useNA = "ifany") %>% addmargins()
#                        singleton
# first_HH_case_age_cat    0  1 Sum
#   Child-first household 13 11  24
#   Adult-first household 36  5  41
#   Sum                   49 16  65

# Number of HHs by HH type and singleton %
singleton_data_HH_with_complete_seq_only %>% 
  mutate(singleton = ifelse(singleton=="1",1,0)) %>%
  group_by(family_id) %>%
  summarise(
    first_HH_case_age_cat = unique(first_HH_case_age_cat),
    n_seqs = n(),
    n_singletons = sum(singleton),
    p_singletons = n_singletons/n_seqs*100,
    .groups = "drop"
  ) %>% 
  select(first_HH_case_age_cat, p_singletons) %>% 
  table(useNA = "ifany") %>% addmargins()
#                        p_singletons
# first_HH_case_age_cat    0 33.3333333333333 100 Sum
#   Child-first household  7                0  11  18
#   Adult-first household  7                3   1  11
#   Sum                   14                3  12  29

# Model fitting + stepwise BIC-based model selection
# -------------------------------
singleton_prob_mdl_reduced <- buildmer(
  # Analyses with these initial models failed to converge, and (1 | family_id) got dropped midway
  # singleton ~ (age_cat * first_HH_case_age_cat + sex + major_lineage + overall_res_end_with_symp_severity) + (1 | family_id),
  # singleton ~ (age_cat + first_HH_case_age_cat + sex + major_lineage + overall_res_end_with_symp_severity) + (1 | family_id),
  # singleton ~ (age_cat + first_HH_case_age_cat + sex + major_lineage ) + (1 | family_id),
  # singleton ~ (age_cat + first_HH_case_age_cat + sex + overall_res_end_with_symp_severity) + (1 | family_id),
  # singleton ~ (age_cat + first_HH_case_age_cat + major_lineage + overall_res_end_with_symp_severity) + (1 | family_id),
  # singleton ~ (age_cat + first_HH_case_age_cat + major_lineage) + (1 | family_id),
  # singleton ~ (first_HH_case_age_cat + major_lineage) + (1 | family_id),
  
  singleton ~ first_HH_case_age_cat + (1 | family_id),
  data = singleton_data_HH_with_complete_seq_only,
  family = binomial,
  buildmerControl = buildmerControl(
    include = ~ (1 | family_id),
    direction = "backward",
    crit = "BIC",
    singular.ok = T,
    args = list(
      control = glmerControl(
        optimizer = "bobyqa",
        optCtrl = list(maxfun = 2e5)
      ) # end glmerControl
    ) # end args list
  ) # end buildmerControl
) # end buildmer

# Examine the reduced model
# -------------------------------
summary(singleton_prob_mdl_reduced@model)
# Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
#  Family: binomial  ( logit )
# Formula: singleton ~ first_HH_case_age_cat + (1 | family_id)
#    Data: singleton_data_HH_with_complete_seq_only
# Control: structure(list(optimizer = c("bobyqa", "bobyqa"), restart_edge = FALSE,      boundary.tol = 1e-05, calc.derivs = NULL, use.last.params = FALSE,  
#     checkControl = list(autoscale = NULL, check.nobs.vs.rankZ = "ignore",          check.nobs.vs.nlev = "stop", check.nlev.gtreq.5 = "ignore",  
#         check.nlev.gtr.1 = "stop", check.nobs.vs.nRE = "stop",          check.rankX = "message+drop.cols", check.scaleX = "warning",  
#         check.formula.LHS = "stop", check.response.not.const = "stop"),      checkConv = list(check.conv.nobsmax = 10000, check.conv.nparmax = 20,  
#         check.conv.grad = list(action = "warning", tol = 0.002,              relTol = NULL), check.conv.singular = list(action = "message",  
#             tol = 1e-04), check.conv.hess = list(action = "warning",              tol = 1e-06)), optCtrl = list(maxfun = 2e+05), tolPwrss = 1e-07,  
#     compDev = TRUE, nAGQ0initStep = TRUE), class = c("glmerControl",  "merControl"))
# 
#       AIC       BIC    logLik -2*log(L)  df.resid 
#      60.3      66.8     -27.1      54.3        62 
# 
# Scaled residuals: 
#      Min       1Q   Median       3Q      Max 
# -0.68616 -0.13184 -0.00847 -0.00835  1.45738 
# 
# Random effects:
#  Groups    Name        Variance Std.Dev.
#  family_id (Intercept) 219.5    14.82   
# Number of obs: 65, groups:  family_id, 29
# 
# Fixed effects:
#                                            Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                   7.199      2.419   2.976 0.002918 ** 
# first_HH_case_age_catAdult-first household  -16.664      4.718  -3.532 0.000412 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# Correlation of Fixed Effects:
#             (Intr)
# fr_HH___A-h -0.826

icc(singleton_prob_mdl_reduced@model)
# # Intraclass Correlation Coefficient
# 
#     Adjusted ICC: 0.985
#   Unadjusted ICC: 0.761

car::Anova(singleton_prob_mdl_reduced@model)
# Analysis of Deviance Table (Type II Wald chisquare tests)
# 
# Response: singleton
#                        Chisq Df Pr(>Chisq)    
# first_HH_case_age_cat 12.475  1  0.0004125 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Estimate singleton odds ratio between "Child-first household" VS "Adult-first household" based on the reduced model
# -------------------------------
emmeans(
  singleton_prob_mdl_reduced@model, 
  pairwise ~ first_HH_case_age_cat, 
  type = "response",
) %>% summary(infer = c(T, T)) %>%
  pluck("contrasts") %>% as.data.frame()
#  contrast                                          odds.ratio       SE  df asymp.LCL    asymp.UCL null z.ratio p.value
#  (Child-first household) / (Adult-first household)   17262373 81444575 Inf  1663.785 179103386813    1   3.532  0.0004
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the log odds ratio scale 
# Tests are performed on the log odds ratio scale

# Estimate singleton rates for "Child-first household" VS "Adult-first household" based on the reduced model
# -------------------------------
emmeans(
  singleton_prob_mdl_reduced@model, 
  ~ first_HH_case_age_cat, 
  type = "response", # "weights"arg doesn't matter as the model contains only 1 fixed effect
) %>% summary(infer = c(T, T)) %>% as.data.frame() #%>%
#   mutate(
#     prob = round(prob * 100, 2),
#     asymp.LCL = round(asymp.LCL * 100, 2),
#     asymp.UCL = round(asymp.UCL * 100, 2),
#   )
#  first_HH_case_age_cat      prob           SE  df asymp.LCL asymp.UCL null z.ratio p.value
#  Child-first household 0.9992536 0.0018042413 Inf 0.9211670 0.9999935  0.5   2.976  0.0029
#  Adult-first household 0.0000775 0.0002359982 Inf 0.0000002 0.0293326  0.5  -3.110  0.0019
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the logit scale 
# Tests are performed on the logit scale

# ###############################
# Cluster size analysis
# ###############################
cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only <- filter(cluster_metadata_hard_pruned_tree, assoc_with_HH_with_complete_seq_dat == "Yes")

# Compute some basic stats
# -------------------------------
cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only %>%
  select(major_lineage, size) %>% 
  table(useNA = "ifany") %>% addmargins()
#              size
# major_lineage  1  2  3  4  5  7 Sum
#    BA.2.75     4  0  1  1  1  0   7
#    BA.2.86     4  4  2  1  0  0  11
#    BA.5        1  0  0  0  0  0   1
#    XBB or XBL  7  5  1  0  0  1  14
#    Sum        16  9  4  2  1  1  33

summary(cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only$size)
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    1       1       2       2       2       7 

sd(cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only$size)
# [1] 1.391941

cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only %>% 
  count(assoc_HH) %>% rename(HH_cluster_count = n) %>% 
  select(HH_cluster_count) %>% 
  table(useNA = "ifany") %>% addmargins()
# HH_cluster_count
#   1   2 Sum 
#  23   5  28 

# Model fitting + stepwise BIC-based model selection with CONWAY-MAXWELL-POISSON REGRESSION model
# -------------------------------
cluster_size_pois_mdl_full_compois <- glmmTMB(
  size ~ first_HH_case_age_cat * major_lineage,
  family = compois(),
  data = cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only
)
# dropping columns from rank-deficient conditional model: first_HH_case_age_catChild-first household:major_lineageBA.5

cluster_size_pois_mdl_reduced_compois <- step(cluster_size_pois_mdl_full_compois, k = log(nrow(cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only)))
summary(cluster_size_pois_mdl_reduced_compois)
#  Family: compois  ( log )
# Formula:          size ~ first_HH_case_age_cat
# Data: cluster_metadata_hard_pruned_tree_HH_with_complete_seq_only
# 
#       AIC       BIC    logLik -2*log(L)  df.resid 
#     104.3     108.8     -49.1      98.3        30 
# 
# 
# Dispersion parameter for compois family (): 0.545 
# 
# Conditional model:
#                                            Estimate Std. Error z value Pr(>|z|)    
# (Intercept)                                  0.9280     0.1183   7.846 4.29e-15 ***
# first_HH_case_age_catChild-first household  -0.5651     0.2063  -2.739  0.00616 ** 
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

sigma(cluster_size_pois_mdl_reduced_compois)
# [1] 0.5452205 # This is equivalent to nu = 1/0.5452205 = 1.83412

car::Anova(cluster_size_pois_mdl_reduced_compois)
# Analysis of Deviance Table (Type II Wald chisquare tests)
# 
# Response: size
#                        Chisq Df Pr(>Chisq)   
# first_HH_case_age_cat 7.5042  1   0.006155 **
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

# Estimate mean cluster size distribution using the CONWAY-MAXWELL-POISSON REGRESSION model
# ------------------------------------
emmeans(
  cluster_size_pois_mdl_reduced_compois, 
  ~ first_HH_case_age_cat, 
  type = "response"
) %>% summary(infer = c(T, T)) %>% as.data.frame()
#  first_HH_case_age_cat response        SE  df asymp.LCL asymp.UCL null z.ratio p.value
#  Adult-first household 2.529412 0.2991657 Inf  2.006060  3.189299    1   7.846 <0.0001
#  Child-first household 1.437500 0.2429441 Inf  1.032169  2.002003    1   2.147  0.0318
# 
# Confidence level used: 0.95 
# Intervals are back-transformed from the log scale 
# Tests are performed on the log scale 

# ###############################
# Cluster timescale analysis
# ###############################
# Prepare data for model fitting
# -------------------------------
cluster_timescale_df_HH_with_complete_seq_only <- filter(cluster_timescale_df, assoc_with_HH_with_complete_seq_dat == "Yes")

nrow(cluster_timescale_df_HH_with_complete_seq_only)
# [1] 33

# Compute some basic stats
# -------------------------------
cluster_timescale_df_HH_with_complete_seq_only$timescale %>% table %>% cumsum
#                0 1.27604000001497 1.70747000000461 2.54478000004838 2.89773499994567 4.00003499998434  7.2098450000135  7.6704750000124 10.1480949999814 
#               21               22               23               24               25               26               27               28               29 
# 12.1738449999293 17.2495350000611 18.2047400000147 19.7308050000208 
#               30               31               32               33 

summary(cluster_timescale_df_HH_with_complete_seq_only$timescale)
#  Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 0.000   0.000   0.000   3.176   2.898  19.731 

sd(cluster_timescale_df_HH_with_complete_seq_only$timescale)
# [1] 5.816948

sum(cluster_timescale_df_HH_with_complete_seq_only$timescale <= 14)
# [1] 30

sum(cluster_timescale_df_HH_with_complete_seq_only$timescale <= 21)
# [1] 33

sum(cluster_timescale_df_HH_with_complete_seq_only$timescale <= 28)
# [1] 33

cluster_timescale_df_HH_with_complete_seq_only %>% 
  group_by(first_HH_case_age_cat) %>%
  summarise(
    n = n(),
    mean_timescale = mean(timescale),
    med_timescale = median(timescale),
  )
#   first_HH_case_age_cat     n mean_timescale med_timescale
#   <chr>                 <int>          <dbl>         <dbl>
# 1 Adult-first household    17           4.97          1.28
# 2 Child-first household    16           1.27          0

cluster_timescale_df_HH_with_complete_seq_only %>% 
  filter(timescale > 0) %>% 
  group_by(first_HH_case_age_cat) %>%
  summarise(
    n = n(),
    mean_timescale = mean(timescale),
    med_timescale = median(timescale),
  )
#   first_HH_case_age_cat     n mean_timescale med_timescale
#   <chr>                 <int>          <dbl>         <dbl>
# 1 Adult-first household     9           9.40          7.67
# 2 Child-first household     3           6.75          7.21

# Model fitting + stepwise BIC-based model selection
# -------------------------------
# We noticed from the previous section that only a few HHs have > 1 cluster
# So we won't fit a mixed-effects model for this either
# We would go fixed-effects only generalized additive models (to account for zero inflation)
cluster_timescale_mdl_full <- gamlss(timescale ~ first_HH_case_age_cat * major_lineage, data = cluster_timescale_df_HH_with_complete_seq_only, family = ZAGA)
cluster_timescale_mdl_reduced <- step(cluster_timescale_mdl_full, k = log(nrow(cluster_timescale_df_HH_with_complete_seq_only)))

# Examine the reduced model
summary(cluster_timescale_mdl_reduced)
# ******************************************************************
# Family:  c("ZAGA", "Zero Adjusted GA") 
# 
# Call:  gamlss(formula = timescale ~ 1, family = ZAGA, data = cluster_timescale_df_HH_with_complete_seq_only) 
# 
# Fitting method: RS() 
# 
# ------------------------------------------------------------------
# Mu link function:  log
# Mu Coefficients:
#             Estimate Std. Error t value Pr(>|t|)    
# (Intercept)   2.1673     0.2321   9.336 2.21e-10 ***
# ---
# Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
# 
# ------------------------------------------------------------------
# Sigma link function:  log
# Sigma Coefficients:
#             Estimate Std. Error t value Pr(>|t|)
# (Intercept)  -0.2180     0.1862   -1.17    0.251
# 
# ------------------------------------------------------------------
# Nu link function:  logit 
# Nu Coefficients:
#             Estimate Std. Error t value Pr(>|t|)
# (Intercept)   0.5596     0.3619   1.546    0.132
# 
# ------------------------------------------------------------------
# No. of observations in the fit:  33 
# Degrees of Freedom for the fit:  3
#       Residual Deg. of Freedom:  30 
#                       at cycle:  2 
#  
# Global Deviance:     118.0574 
#             AIC:     124.0574 
#             SBC:     128.547 
# ******************************************************************

# Estimate zero adjusted cluster_timescale
# -------------------------------
emmeans(cluster_timescale_mdl_reduced, ~ 1, type = "response") %>% as.data.frame() %>%
  mutate(
    response = round(response, 2),
    asymp.LCL = round(asymp.LCL, 2),
    asymp.UCL = round(asymp.UCL, 2)
  )
#         1 response       SE  df asymp.LCL asymp.UCL
# 1 overall     8.73 2.027605 Inf      5.54     13.77
